# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      yarn install
      echo 'The following "yarn" command (if executed) installs the "cross-env"'
      echo 'dependency into the local "node_modules" directory, which will ultimately'
      echo 'be stored in the Jenkins home directory.'

      set -x
      set +x

      echo 'The following "yarn" command tests that your simple Node.js/React'
      echo 'application renders satisfactorily. This command actually invokes the test'
      echo 'runner Jest (https://facebook.github.io/jest/).'
      set -x
      yarn test

      yarn build
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'scripts/tests/'

